export const INFORMATION_FETCH_REQUEST = "INFORMATION_FETCH_REQUEST";
export const INFORMATION_FETCH_SUCCESS = "INFORMATION_FETCH_SUCCESS";
export const INFORMATION_FETCH_FAIL = "INFORMATION_FETCH_FAIL";